queen_changed

diff --git a/queen b/queen
--- a/queen
+++ b/queen
@@ -1,1 +1,38 @@
-212.139.211.7
+#!/bin/bash
+PP="${0%/*}"
+source "$PP/queen.ini" 
+echo "
+==============================  $(date)  ================================="
+localStore="$PP/queenIP"
+regexIp="([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])"
+resolvedIp=$(dig +short myip.opendns.com @resolver1.opendns.com)
+gitStoredIp=$(curl https://raw.githubusercontent.com/snn1024a/aridzuka/master/queenIP)
+localStoredIp=$(cat $localStore)
+	if [[ $resolvedIp =~ ^$regexIp\.$regexIp\.$regexIp\.$regexIp$ ]]
+	then echo "=== Resolved-$resolvedIp it's valid ip"
+		if [[ $resolvedIp == $gitStoredIp ]]
+		then echo "=== Resolved-$resolvedIp is the same as git stored-$gitStoredIp. No action required."
+		     exit 0
+		else echo "=== Resolved-$resolvedIp is different than git stored-$gitStoredIp. Must be updated online."
+		     curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Queen IP: $resolvedIp\"}" $url
+		     echo $resolvedIp > $localStore
+		     git --git-dir="$PP/.git" --work-tree="$PP/" add --verbose $localStore
+			if [ $? -eq 0 ]
+			then sleep 1
+			     echo "=== git add OK"
+			     git --git-dir="$PP/.git" --work-tree="$PP/" commit --verbose -am "queen_changed"
+				if [ $? -eq 0 ]
+                	        then sleep 3
+				     echo "=== git commit OK"
+				     git --git-dir="$PP/.git" --work-tree="$PP/" push --verbose
+                                	if [ $? -eq 0 ]
+                                	then echo "=== git push OK"
+                                	else echo "=== git push FAIL"
+                                	fi
+				else echo "=== git commit FAIL"
+                                fi
+			else echo "=== git add FAIL"
+			fi
+		fi
+	else echo "=== Resolved-$resolvedIp not valid ip"
+	fi
